project:
  type: book
  output-dir: docs

book:
  favicon: favicon.png
  title: "Incertitudes..."
  output-file: "incertitudes"
  author: "Lucas Voirin"
  date: today
  chapters:
    - index.qmd
    - variables_distributions.qmd
    - anatomie_modele.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    search: true
    tools:
      - text: Ouvrir la version pdf
        icon: file-earmark-pdf-fill
        href: https://lucasvoirin.github.io/incertitudes/incertitudes.pdf
      - text: Ouvrir le repo github
        icon: github
        href: https://github.com/lucasvoirin/incertitudes 
  # navbar:
  #   background: primary
  #   logo-href: https://lucasvoirin.github.io
  #   title: Lucas Voirin
  #   search: false
  #   left:
  #     - text: "Research"
  #       href: https://lucasvoirin.github.io/research/

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 6
    fig-height: 3
    mainfont: Inter
  pdf:
    documentclass: scrreprt
    fig-width: 6
    fig-height: 3
    fontfamily: inter
    mainfont: Inter
